LbRssrBundle_homepage:
    pattern:  /home
    defaults: { _controller: "LbRssrBundle:Default:index" }
    
LbRssrBundle_items:
    pattern:  /items.{_format}
    defaults: { _controller: LbRssrBundle:Default:items, _format: json }
    requirements: { _format: (xml|json), _method: GET }

LbRssrBundle_provide:
    pattern:  /provide
    defaults: { _controller: LbRssrBundle:Default:provide }
    
LbRssrBundle_admin:
    resource: "routing/source.yml"
    prefix:  /admin
