<?php

namespace Lb\RssrBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceRepository extends EntityRepository
{
	
	public function getAllValidRss()
	{
		return $this->createQueryBuilder('s')
					->where('s.etat = :etat')
						->setParameter('etat', 1)
					->getQuery()
				    ->getResult();
	}
	
}